name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "public/**"
      - "src/**"
      - "astro.config.mjs"
      - "package.json"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: withastro/action@v3
        with:
          path: .
          node-version: 22
          # `package-manager` option is determined by `packageManager` in `package.json`

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
